modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

# Mixin configs applied by this mod.
[[mixins]]
config="create_expansion.mixins.json"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
description='''
Example mod description.
'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="create"
    type="required"
    versionRange="[6.0.10,6.1.0)"
    # AFTER so our datapack loads after Create's, letting us override its recipes.
    ordering="AFTER"
    side="BOTH"